codecov:
  require_ci_to_pass: true

# ignore files in demo package
ignore:
  - "src/main/java/demo"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%  # project coverage can drop
    patch:
      default:
        target: 70%    # required diff coverage value
